const game: GameContext = {
  state,
  player: getPlayer,
  randomRange,
  normalize,
  rotate: rotateVector,
  findEnemyById,
  findNearestEnemies,
  spawnProjectile,
  spawnZone,
  spawnMine,
  spawnBeam,
  spawnStrike,
  spawnScythe,
  grantGold,
  grantRelic,
  cooldown: scaleCooldown,
  amount: scaleAmount,
  attackSpeed: scaleAttackSpeed,
  area: scaleArea,
  blastArea: scaleBlastArea,
  hasPassive,
  withEcho,
  damageEnemy,
  areaDamage,
  damageEnemiesAlongLine,
  applySlow,
  addParticles,
};
